/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tp.GUI;

/**
 *
 * @author aluno
 */
public class CadastroDeUsuario extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public CadastroDeUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRAR USUARIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 569, -1));

        jButton1.setText("CADASTRAR");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 114, 32));

        jLabel2.setText("CPF:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 32));

        jTextField2.setText("000.000.000-00");
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 162, 32));

        jTextField4.setText("NOME AQUI");
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 162, 32));

        jLabel4.setText("NOME:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, 32));

        jTextField5.setText("(062)42895-4762");
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 170, 140, 32));

        jLabel5.setText("TELEFONE:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, 32));

        jTextField6.setText("UmEmail@Aqui.com.br");
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 160, 32));

        jLabel6.setText("EMAIL:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 32));

        jTextField7.setText("**UM NUMERO AI**");
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 140, 32));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CNH");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 200, 32));

        jLabel8.setText("CATEGORIA:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, 32));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, 30));

        jLabel9.setText("NUMERO:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, 32));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
